# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ui_kganttdatetimetimelinedialog.h
SOURCES += ./KGantt_autogen/mocs_compilation.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttglobal.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttprintingcontext.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttview.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttstyleoptionganttitem.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttgraphicsview.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttabstractrowcontroller.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kgantttreeviewrowcontroller.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttlistviewrowcontroller.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttgraphicsscene.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttgraphicsitem.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttconstraint.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttconstraintproxy.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttconstraintgraphicsitem.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttitemdelegate.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttforwardingproxymodel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttsummaryhandlingproxymodel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttproxymodel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttconstraintmodel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttabstractgrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttdatetimegrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttlegend.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttdatetimetimeline.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttdatetimetimelinedialog.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/kganttpenstylecombobox.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/unittest/test.cpp \
    ../../../../src/kdiagram-2.8.0/src/KGantt/unittest/testregistry.cpp \
    ./ECMQmLoader-kgantt_qt.cpp
FORMS += ../../../../src/kdiagram-2.8.0/src/KGantt/kganttdatetimetimelinedialog.ui
