# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./ui_KChartDatasetSelector.h
SOURCES += ./KChart_autogen/mocs_compilation.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartMeasure.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractCoordinatePlane.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartChart.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartWidget.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractAreaBase.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractArea.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartTextArea.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractAreaWidget.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractAxis.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractProxyModel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractGrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAttributesModel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartBackgroundAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartDatasetProxyModel.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartDatasetSelector.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartDataValueAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartDiagramObserver.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartFrameAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartGridAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartRulerAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartHeaderFooter.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartLayoutItems.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartLegend.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartLineAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartMarkerAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartPaintContext.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartPalette.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartPosition.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartRelativePosition.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KTextDocument.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartTextAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartAbstractThreeDAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartThreeDLineAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartTextLabelCache.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/ChartGraphicsItem.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/ReverseMapper.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartValueTrackerAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartPrintingParameters.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/KChartModelDataCache_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartAbstractCartesianDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartCartesianCoordinatePlane.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartCartesianAxis.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartCartesianGrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartBarDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartThreeDBarAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartBarAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartStockBarAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartStockDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartStockDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLineDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLineDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartCartesianDiagramDataCompressor_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartPlotter.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartPlotter_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartPlotterDiagramCompressor.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLeveyJenningsCoordinatePlane.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLeveyJenningsDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLeveyJenningsDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLeveyJenningsGrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLeveyJenningsGridAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/KChartLeveyJenningsAxis.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/PaintingHelpers_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartNormalPlotter_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartPercentPlotter_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartStackedPlotter_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartStackedLyingBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartStackedLineDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartStackedBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartPercentBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartPercentLyingBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartPercentLineDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartNormalBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartNormalLyingBarDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Cartesian/DiagramFlavors/KChartNormalLineDiagram_p.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartPolarCoordinatePlane.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartRadarCoordinatePlane.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartAbstractPieDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartAbstractPolarDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartPolarGrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartRadarGrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartPieDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartPolarDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartRadarDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartRingDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartPieAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Polar/KChartThreeDPieAttributes.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/KChartTernaryAxis.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/KChartTernaryGrid.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/TernaryPoint.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/TernaryConstants.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/KChartTernaryCoordinatePlane.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/KChartAbstractTernaryDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/KChartTernaryPointDiagram.cpp \
    ../../../../src/kdiagram-2.8.0/src/KChart/Ternary/KChartTernaryLineDiagram.cpp \
    ./qrc_KChart_LeveyJennings_resources.cpp \
    ./ECMQmLoader-kchart_qt.cpp \
    ./moc_KChartEnums.cpp
FORMS += ../../../../src/kdiagram-2.8.0/src/KChart/KChartDatasetSelector.ui
RESOURCES += ../../../../src/kdiagram-2.8.0/src/KChart/KChart_LeveyJennings_resources.qrc
