// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef OKULAR_VERSION_H
#define OKULAR_VERSION_H

#define OKULAR_VERSION_STRING "20.12.2"
#define OKULAR_VERSION_MAJOR 20
#define OKULAR_VERSION_MINOR 12
#define OKULAR_VERSION_PATCH 2
#define OKULAR_VERSION ((20<<16)|(12<<8)|(2))

#endif
