# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.



SOURCES += ./kxmlgui_unittest_autogen/mocs_compilation.cpp \
    ../../autotests/kxmlgui_unittest.cpp
