// This file is generated by kconfig_compiler_kf5 from pdfsettings.kcfg.
// All changes you do to this file will be lost.
#ifndef PDFSETTINGS_H
#define PDFSETTINGS_H

#include <kconfigskeleton.h>
#include <QCoreApplication>
#include <QDebug>

class PDFSettings : public KConfigSkeleton
{
  public:
    class EnumEnhanceThinLines
    {
      public:
      enum type { No, Solid, Shape, COUNT };
    };

    static PDFSettings *self();
    ~PDFSettings();

    /**
      Set EnhanceThinLines
    */
    static
    void setEnhanceThinLines( int v )
    {
      if (!self()->isEnhanceThinLinesImmutable())
        self()->mEnhanceThinLines = v;
    }

    /**
      Get EnhanceThinLines
    */
    static
    int enhanceThinLines()
    {
      return self()->mEnhanceThinLines;
    }

    /**
      Is EnhanceThinLines Immutable
    */
    static
    bool isEnhanceThinLinesImmutable()
    {
      return self()->isImmutable( QStringLiteral( "EnhanceThinLines" ) );
    }

  protected:
    PDFSettings();
    friend class PDFSettingsHelper;


    // General
    int mEnhanceThinLines;

  private:
};

#endif

