// This file is generated by kconfig_compiler_kf5 from pdfsettings.kcfg.
// All changes you do to this file will be lost.

#include "pdfsettings.h"

#include <qglobal.h>
#include <QFile>

class PDFSettingsHelper
{
  public:
    PDFSettingsHelper() : q(nullptr) {}
    ~PDFSettingsHelper() { delete q; }
    PDFSettingsHelper(const PDFSettingsHelper&) = delete;
    PDFSettingsHelper& operator=(const PDFSettingsHelper&) = delete;
    PDFSettings *q;
};
Q_GLOBAL_STATIC(PDFSettingsHelper, s_globalPDFSettings)
PDFSettings *PDFSettings::self()
{
  if (!s_globalPDFSettings()->q) {
    new PDFSettings;
    s_globalPDFSettings()->q->read();
  }

  return s_globalPDFSettings()->q;
}

PDFSettings::PDFSettings( )
  : KConfigSkeleton( QStringLiteral( "okular-generator-popplerrc" ) )
{
  Q_ASSERT(!s_globalPDFSettings()->q);
  s_globalPDFSettings()->q = this;
  setCurrentGroup( QStringLiteral( "General" ) );

  QList<KConfigSkeleton::ItemEnum::Choice> valuesEnhanceThinLines;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QStringLiteral("No");
    valuesEnhanceThinLines.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QStringLiteral("Solid");
    valuesEnhanceThinLines.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QStringLiteral("Shape");
    valuesEnhanceThinLines.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemEnhanceThinLines;
  itemEnhanceThinLines = new KConfigSkeleton::ItemEnum( currentGroup(), QStringLiteral( "EnhanceThinLines" ), mEnhanceThinLines, valuesEnhanceThinLines, EnumEnhanceThinLines::No );
  addItem( itemEnhanceThinLines, QStringLiteral( "EnhanceThinLines" ) );
}

PDFSettings::~PDFSettings()
{
  s_globalPDFSettings()->q = nullptr;
}

